---
title: "hw4_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

rest_clean =
  rest_inspec %>%
  mutate(zipcode = as.character(zipcode)) %>%
  drop_na(score) %>%
  mutate(
    inspec_year = as.numeric(format(inspection_date, "%Y"))
  ) %>%
  filter(inspec_year == 2016) %>%
  select (boro, zipcode, critical_flag, cuisine_description, inspection_date, inspec_year, score)
```

```{r}

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_clean %>%
  mutate(
    boro = na_if(boro, "Missing") 
  ) %>%
  plot_ly(x = ~boro, y = ~score, type = "box", color = ~boro, 
          colors = "viridis", marker = list(opacity = 0.1)) %>%
  layout(
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Restaurant Inspection Score")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_clean %>%
  filter (boro == "QUEENS") %>%
      filter (critical_flag == "Critical")%>%
  count(zipcode)%>%
  mutate(zipcode = fct_reorder(zipcode, n))%>%
  plot_ly( x = ~zipcode, y = ~n, type = "bar", 
           color = ~zipcode, colors = "viridis"
  )
```

### Chart C

```{r}

```

